[package]
name = "toylang-lexer"
version = "0.1.0"
authors = ["Rafał Galczak <r.galczak@gmail.com>"]
edition = "2018"

[lib]
name = "lexer"
path = "src/lib.rs"


[dependencies]
toylang-utility = { path = "../utility" }
toylang-source = { path = "../source" }
toylang-error = { path = "../error" }